import "./globals.css";
import { Raleway } from "next/font/google";
import Header from './components/Navbar'

const raleway = Raleway({ subsets: ["latin"] });

export const metadata = {
  title: "Taylie's Blog",
  description: "Generated by Taylie Whitworth",
  favicon: "/images/smileyFace.png",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <Header />
        <main className="mt-20">{children}</main>
      </body>
    </html>
  );
}
